[package]
name = "gridsim-ui"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
description = "A library for rendering grids from gridsim"
license = "MIT"
documentation = "https://docs.rs/gridsim-ui/"
repository = "https://github.com/vadixidav/gridsim-ui"

[dependencies]
gridsim = "0.1.2"
glium = "0.19.0"
cgmath = "0.16.0"
