[package]
name = "gridsim-ui"
version = "0.2.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
description = "A library for rendering grids from gridsim"
license = "MIT"
documentation = "https://docs.rs/gridsim-ui/"
repository = "https://github.com/vadixidav/gridsim-ui"

[dependencies]
gridsim = "0.2.0"
rayon = "1.0.1"
glium = { git = "https://github.com/glium/glium" }
cgmath = "0.16.0"

flamer = { version = "0.2.2", optional = true }
flame = { version = "0.2.2", optional = true }

[features]
default = []
flame_it = ["flame", "flamer"]
